# syntax=docker/dockerfile:1
FROM ruby:2.4.9-alpine AS GEMS

RUN apk add --no-cache \
    postgresql \
    postgresql-client \
    postgresql-dev \
    build-base

COPY . /app
WORKDIR /app

#COPY Gemfile /app/
#COPY Gemfile.lock /usr/app/
RUN bundle install


FROM ruby:2.4.9-alpine
RUN apk add --no-cache \
    postgresql-client \
    build-base
COPY --from=GEMS /usr/local/bundle/ /usr/local/bundle/

COPY . /app
WORKDIR /app

